name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    #- name: List out directory contents
    #  run: |
    #    echo "Listing the contents of the GitHub workspace directory"
    #    ls ${{ github.workspace }}

    #    echo "Recursively listing all contents of the current directory"
    #    ls -R
    - name: Run dotnet publish
      run: dotnet publish ${{ github.workspace }}/AnimalAdoption.Web.Portal/AnimalAdoption.Web.Portal.csproj --output ./build/ --no-build
    - uses: actions/upload-artifact@v2
      with:
        name: animal-artifact
        path:  ${{ github.workspace }}/build/
   
      

