name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/DevOpsGitHub-Team-1/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Run Unit Testing
      run: dotnet test  ${{ github.workspace }}/AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj --no-restore --verbosity n
    - name: Build
      run: dotnet build --configuration Release --no-restore
    #- name: List out directory contents
    #  run: |
    #    echo "Listing the contents of the GitHub workspace directory"
    #    ls ${{ github.workspace }}

    #    echo "Recursively listing all contents of the current directory"
    #    ls -R
    - name: Run dotnet publish
      run: dotnet publish ${{ github.workspace }}/AnimalAdoption.Web.Portal/AnimalAdoption.Web.Portal.csproj --output ./build/ --configuration Release --no-build
    - uses: actions/upload-artifact@v2
      with:
        name: animal-artifact
        path:  ${{ github.workspace }}/build/

    - name: Run dotnet pack
      run: dotnet pack ${{ github.workspace }}/AnimalAdoption.Common.Logic/AnimalAdoption.Common.Logic.csproj --configuration Release --no-build

    - name: Run dotnet nuget push
      run: dotnet nuget push ${{ github.workspace }}/AnimalAdoption.Common.Logic/bin/Release/*.nupkg
   
      

